import Mathlib

open MvPolynomial Set Ideal
open scoped MonomialOrder

/-!
# Gröbner Bases for Multivariate Polynomial Rings

Formalization of Hassett "Introduction to Algebraic Geometry", Chapter 2.

* Hassett, *Introduction to Algebraic Geometry*, Chapter 2
* Cox–Little–O'Shea, *Ideals, Varieties and Algorithms*, Chapter 2
* Becker–Weispfenning (1993)
-/

namespace MonomialOrder

variable {σ : Type*} (m : MonomialOrder σ) {k : Type*} [Field k]

/-! ### 1. The Division Algorithm -/

/-- **Multivariate Division Algorithm** (Hassett Thm 2.1.3).
For any family of nonzero polynomials `b : ι → k[σ]` and any `f`, there exist
quotients `q : ι →₀ k[σ]` and a remainder `r` such that
  `f = ∑ᵢ qᵢ · bᵢ + r`
where the degree of each `bᵢ · qᵢ` does not exceed that of `f`, and no monomial
of `r` is divisible by the leading monomial of any `bᵢ`. -/
theorem division_algorithm {ι : Type*} (b : ι → MvPolynomial σ k)
    (hb : ∀ i, b i ≠ 0) (f : MvPolynomial σ k) :
    ∃ (q : ι →₀ MvPolynomial σ k) (r : MvPolynomial σ k),
      f = Finsupp.linearCombination _ b q + r ∧
      (∀ i, m.degree (b i * q i) ≼[m] m.degree f) ∧
      (∀ c ∈ r.support, ∀ i, ¬ m.degree (b i) ≤ c) :=
  m.div (fun i => m.isUnit_leadingCoeff.mpr (hb i)) f

/-! ### 2. The Initial Ideal -/

/-- The **initial ideal** (leading term ideal) of `I` with respect to `m`:
the ideal generated by `{lterm(f) | f ∈ I}`. -/
noncomputable def initialIdeal (I : Ideal (MvPolynomial σ k)) :
    Ideal (MvPolynomial σ k) :=
  Ideal.span (m.leadingTerm '' (I : Set (MvPolynomial σ k)))

variable {m}

/-- The leading term of any `f ∈ I` lies in the initial ideal of `I`. -/
lemma leadingTerm_mem_initialIdeal {I : Ideal (MvPolynomial σ k)}
    {f : MvPolynomial σ k} (hf : f ∈ I) :
    m.leadingTerm f ∈ m.initialIdeal I :=
  Ideal.subset_span ⟨f, hf, rfl⟩

/-- The initial ideal is monotone. -/
lemma initialIdeal_mono {I J : Ideal (MvPolynomial σ k)} (h : I ≤ J) :
    m.initialIdeal I ≤ m.initialIdeal J :=
  Ideal.span_mono (Set.image_mono h)

/-- The span of leading terms of `G` embeds into the initial ideal of `Ideal.span G`. -/
lemma span_leadingTerms_le_initialIdeal (G : Set (MvPolynomial σ k)) :
    Ideal.span (m.leadingTerm '' G) ≤ m.initialIdeal (Ideal.span G) :=
  Ideal.span_mono (Set.image_mono Ideal.subset_span)

/-- Over a field, the ideal spanned by `{lterm g | g ∈ G}` equals the monomial ideal
`span {x^(deg g) | g ∈ G, g ≠ 0}`, because nonzero scalars are units.

*Proof sketch*:
- (⊆): `lterm g = leadingCoeff(g) • monomial(deg g, 1)`, so `lterm g ∈ span{monomial(deg h,1)}`.
- (⊇): `monomial(deg g, 1) = (leadingCoeff g)⁻¹ • lterm g ∈ span{lterm h}`. -/
lemma span_leadingTerm_eq_span_leadingMonomial (G : Set (MvPolynomial σ k)) :
    Ideal.span (m.leadingTerm '' G) =
      Ideal.span ((fun s : σ →₀ ℕ => monomial s (1 : k)) ''
        (m.degree '' (G \ {0}))) := by
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro _ ⟨g, hgG, rfl⟩
    simp only [SetLike.mem_coe]
    by_cases hg0 : g = 0
    · simp [hg0]
    · have heq : m.leadingTerm g = m.leadingCoeff g • monomial (m.degree g) (1 : k) := by
        simp [leadingTerm, smul_monomial]
      rw [heq, Algebra.smul_def]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span
        ⟨m.degree g, Set.mem_image_of_mem _ (by simp [hgG, hg0]), rfl⟩)
  · apply Ideal.span_le.mpr
    rintro _ ⟨d, hd, rfl⟩
    simp only [SetLike.mem_coe]
    obtain ⟨g, hg_diff, rfl⟩ := hd
    simp only [Set.mem_diff, Set.mem_singleton_iff] at hg_diff
    obtain ⟨hgG, hg0⟩ := hg_diff
    have heq : monomial (m.degree g) (1 : k) =
        (m.leadingCoeff g)⁻¹ • m.leadingTerm g := by
      simp [leadingTerm, smul_monomial,
            inv_mul_cancel₀ (m.leadingCoeff_ne_zero_iff.mpr hg0)]
    change monomial (m.degree g) (1 : k) ∈ Ideal.span (m.leadingTerm '' G)
    rw [heq, Algebra.smul_def]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨g, hgG, rfl⟩)

/-! ### 3. Gröbner Bases -/

/-- **Gröbner Basis** (Hassett Def 2.2.1 / Cox–Little–O'Shea Def 5, §2.5).
A finite subset `G` of an ideal `I` is a Gröbner basis for `I` if:
1. every element of `G` lies in `I`, and
2. the initial ideal of `I` is generated by the leading terms of `G`. -/
def IsGroebnerBasis (I : Ideal (MvPolynomial σ k))
    (G : Finset (MvPolynomial σ k)) : Prop :=
  (∀ g ∈ G, g ∈ I) ∧
  m.initialIdeal I = Ideal.span (m.leadingTerm '' (G : Set (MvPolynomial σ k)))

namespace IsGroebnerBasis

/-- Elements of a Gröbner basis lie in `I`. -/
lemma mem_ideal {I : Ideal (MvPolynomial σ k)} {G : Finset (MvPolynomial σ k)}
    (hG : m.IsGroebnerBasis I G) {g : MvPolynomial σ k} (hg : g ∈ G) : g ∈ I :=
  hG.1 g hg

/-- The initial ideal of `I` is spanned by the leading terms of `G`. -/
lemma initialIdeal_eq {I : Ideal (MvPolynomial σ k)} {G : Finset (MvPolynomial σ k)}
    (hG : m.IsGroebnerBasis I G) :
    m.initialIdeal I = Ideal.span (m.leadingTerm '' (G : Set (MvPolynomial σ k))) :=
  hG.2

/-- **Key property**: for every nonzero `f ∈ I`, some nonzero `g ∈ G` has
`m.degree g ≤ m.degree f`, i.e., `lm(g)` divides `lm(f)`. -/
theorem leadingDeg_dvd {I : Ideal (MvPolynomial σ k)} {G : Finset (MvPolynomial σ k)}
    (hG : m.IsGroebnerBasis I G) {f : MvPolynomial σ k}
    (hf : f ∈ I) (hf0 : f ≠ 0) :
    ∃ g ∈ G, g ≠ 0 ∧ m.degree g ≤ m.degree f := by
  -- Step 1: lterm(f) lies in the initial ideal = span{lterm g | g ∈ G}.
  have hlt_init : m.leadingTerm f ∈ m.initialIdeal I :=
    Ideal.subset_span ⟨f, hf, rfl⟩
  -- Step 2: Rewrite the initial ideal as a monomial ideal.
  rw [hG.initialIdeal_eq, span_leadingTerm_eq_span_leadingMonomial] at hlt_init
  -- Step 3: Apply the monomial membership criterion.
  rw [mem_ideal_span_monomial_image] at hlt_init
  -- Step 4: m.degree f is in the support of lterm(f).
  have hsupp : m.degree f ∈ (m.leadingTerm f).support := by
    classical
    simp [leadingTerm, support_monomial, m.leadingCoeff_ne_zero_iff.mpr hf0]
  -- Step 5: Extract witness from G \ {0} (so it is nonzero).
  obtain ⟨si, hsi_mem, hle⟩ := hlt_init (m.degree f) hsupp
  obtain ⟨g, hg_diff, hdeg⟩ := hsi_mem
  simp only [Set.mem_diff, Finset.mem_coe, Set.mem_singleton_iff] at hg_diff
  exact ⟨g, hg_diff.1, hg_diff.2, hdeg ▸ hle⟩

/-- A Gröbner basis generates `I` (requires all basis elements to be nonzero). -/
lemma span_eq {I : Ideal (MvPolynomial σ k)} {G : Finset (MvPolynomial σ k)}
    (hG : m.IsGroebnerBasis I G) (hG0 : ∀ g : G, (g : MvPolynomial σ k) ≠ 0) :
    Ideal.span (G : Set (MvPolynomial σ k)) = I := by
  apply le_antisymm (Ideal.span_le.mpr hG.1)
  intro f hf
  set b := fun g : G => (g : MvPolynomial σ k)
  obtain ⟨q, r, hfqr, _, hr⟩ := m.div (fun g : G => m.isUnit_leadingCoeff.mpr (hG0 g)) f
  -- ∑ qᵢgᵢ ∈ Ideal.span G.
  have hsum_span : Finsupp.linearCombination _ b q ∈ Ideal.span (G : Set (MvPolynomial σ k)) := by
    simp only [Finsupp.linearCombination, Finsupp.lsum_apply, Finsupp.sum,
               LinearMap.smulRight_apply, LinearMap.id_coe, id]
    exact sum_mem (fun g _ => Ideal.mul_mem_left _ _ (Ideal.subset_span (Finset.mem_coe.mpr g.2)))
  -- Remainder r = f − ∑ qᵢgᵢ ∈ I.
  have hG_le : Ideal.span (G : Set (MvPolynomial σ k)) ≤ I :=
    Ideal.span_le.mpr (fun g hg => hG.mem_ideal (Finset.mem_coe.mp hg))
  have hr_mem : r ∈ I := by
    have : r = f - Finsupp.linearCombination _ b q := by linear_combination -hfqr
    rw [this]; exact I.sub_mem hf (hG_le hsum_span)
  -- r = 0: if not, leadingDeg_dvd contradicts the remainder condition.
  have hr0 : r = 0 := by
    by_contra hr0
    obtain ⟨g, hgG, -, hdvd⟩ := leadingDeg_dvd hG hr_mem hr0
    exact absurd hdvd (hr (m.degree r) (m.degree_mem_support hr0) ⟨g, hgG⟩)
  rw [hr0, add_zero] at hfqr; exact hfqr ▸ hsum_span

end IsGroebnerBasis

/-! ### 4. Reduction to Zero -/

/-- `f` **reduces to zero** modulo `b : ι → k[σ]` if `f = ∑ᵢ qᵢ · bᵢ` with the
degree of each `bᵢ · qᵢ` bounded by `m.degree f`. -/
def ReducesToZero {ι : Type*} (b : ι → MvPolynomial σ k)
    (_ : ∀ i, b i ≠ 0) (f : MvPolynomial σ k) : Prop :=
  ∃ (q : ι →₀ MvPolynomial σ k),
    f = Finsupp.linearCombination _ b q ∧
    ∀ i, m.degree (b i * q i) ≼[m] m.degree f

/-- The zero polynomial reduces to zero modulo any family. -/
lemma reducesToZero_zero {ι : Type*} (b : ι → MvPolynomial σ k)
    (hb : ∀ i, b i ≠ 0) : m.ReducesToZero b hb 0 :=
  ⟨0, by simp, by simp⟩

/-- If `f` reduces to zero modulo `b`, then `f ∈ Ideal.span (range b)`. -/
lemma mem_span_of_reducesToZero {ι : Type*} (b : ι → MvPolynomial σ k)
    (hb : ∀ i, b i ≠ 0) {f : MvPolynomial σ k}
    (hred : m.ReducesToZero b hb f) :
    f ∈ Ideal.span (Set.range b) := by
  obtain ⟨q, hq, _⟩ := hred
  rw [hq]
  simp only [Finsupp.linearCombination, Finsupp.lsum_apply, Finsupp.sum,
             LinearMap.smulRight_apply, LinearMap.id_coe, id]
  exact sum_mem (fun i _ => Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩))

/-! ### 5. Membership Criterion -/

/-- **Ideal Membership Criterion** (Hassett Thm 2.3.1 / Cox–Little–O'Shea Thm 1, §2.6).
`G` is a Gröbner basis for `I` ⟹ `f ∈ I ↔ f` reduces to 0 mod `G`.

*(→)* Well-founded induction on `m.degree f` using `leadingDeg_dvd`.
*(←)* Each `gᵢ ∈ G ⊆ I`, so `∑ qᵢgᵢ ∈ I`. -/
theorem mem_ideal_iff_reducesToZero (I : Ideal (MvPolynomial σ k))
    (G : Finset (MvPolynomial σ k)) (hGbasis : m.IsGroebnerBasis I G)
    (hG0 : ∀ g : G, (g : MvPolynomial σ k) ≠ 0) (f : MvPolynomial σ k) :
    f ∈ I ↔ m.ReducesToZero (fun g : G => (g : MvPolynomial σ k)) hG0 f := by
  constructor
  · -- (→) Apply the division algorithm; the remainder must be 0 by leadingDeg_dvd.
    intro hf
    set b := fun g : G => (g : MvPolynomial σ k)
    obtain ⟨q, r, hfqr, hdeg, hr⟩ := m.div (fun g : G => m.isUnit_leadingCoeff.mpr (hG0 g)) f
    -- The linear combination lies in I (each g ∈ G ⊆ I).
    have hG_le : Ideal.span (G : Set (MvPolynomial σ k)) ≤ I :=
      Ideal.span_le.mpr (fun g hg => hGbasis.mem_ideal (Finset.mem_coe.mp hg))
    have hsum_I : Finsupp.linearCombination _ b q ∈ I := hG_le (by
      simp only [Finsupp.linearCombination, Finsupp.lsum_apply, Finsupp.sum,
                 LinearMap.smulRight_apply, LinearMap.id_coe, id]
      exact sum_mem (fun g _ => Ideal.mul_mem_left _ _ (Ideal.subset_span (Finset.mem_coe.mpr g.2))))
    -- The remainder r ∈ I.
    have hr_mem : r ∈ I := by
      have : r = f - Finsupp.linearCombination _ b q := by linear_combination -hfqr
      rw [this]; exact I.sub_mem hf hsum_I
    -- r = 0 by the same contradiction argument.
    have hr0 : r = 0 := by
      by_contra hr0
      obtain ⟨g, hgG, -, hdvd⟩ := hGbasis.leadingDeg_dvd hr_mem hr0
      exact absurd hdvd (hr (m.degree r) (m.degree_mem_support hr0) ⟨g, hgG⟩)
    -- f = ∑ qᵢgᵢ with the required degree bounds.
    rw [hr0, add_zero] at hfqr
    exact ⟨q, hfqr, hdeg⟩
  · intro ⟨q, hq, _⟩
    rw [hq]
    simp only [Finsupp.linearCombination, Finsupp.lsum_apply, Finsupp.sum,
               LinearMap.smulRight_apply, LinearMap.id_coe, id]
    exact sum_mem (fun g _ => Ideal.mul_mem_left _ _ (hGbasis.mem_ideal g.2))

/-! ### 6. Buchberger's Criterion -/

/-! #### Helper lemmas for the induction step -/

/-- Degree of a finite sum is `< δ` when every term is. -/
private lemma degree_sum_lt_of_forall_lt {ι : Type*} {s : Finset ι}
    {f : ι → MvPolynomial σ k} {δ : m.syn} (hδ : ⊥ < δ)
    (h : ∀ i ∈ s, m.toSyn (m.degree (f i)) < δ) :
    m.toSyn (m.degree (∑ i ∈ s, f i)) < δ :=
  lt_of_le_of_lt m.degree_sum_le ((Finset.sup_lt_iff hδ).mpr h)

/-- If `p * q` achieves syn-degree `δ` and `p, q ≠ 0`, then the tail `(p - LT p) * q`
has syn-degree `< δ`. -/
private lemma degree_tail_mul_lt_of_top_degree {p q : MvPolynomial σ k} {δ : m.syn}
    (hp : p ≠ 0) (hq : q ≠ 0) (hδ : ⊥ < δ)
    (hpq : m.toSyn (m.degree (p * q)) = δ) :
    m.toSyn (m.degree ((p - m.leadingTerm p) * q)) < δ := by
  by_cases htail : p - m.leadingTerm p = 0
  · simp only [htail, zero_mul, degree_zero, map_zero]
    rwa [← m.bot_eq_zero]
  · -- Since tail ≠ 0, degree p ≠ 0 (else support ⊆ {0} forces p = LT p).
    have hdeg_ne : m.degree p ≠ 0 := by
      intro h
      apply htail; apply sub_eq_zero_of_eq
      have hsupp : ∀ d ∈ p.support, d = 0 := fun d hd => by
        have hle := m.le_degree hd; rw [h] at hle
        exact m.toSyn.injective (le_antisymm hle (m.toSyn_monotone bot_le))
      haveI : DecidableEq σ := Classical.decEq σ
      ext d
      unfold MonomialOrder.leadingTerm MonomialOrder.leadingCoeff
      simp only [coeff_monomial, h]
      split_ifs with hd
      · exact congr_arg p.coeff hd.symm
      · exact Finsupp.notMem_support_iff.mp (fun hmem => hd (hsupp d hmem).symm)
    have hdeg_sum : m.toSyn (m.degree p) + m.toSyn (m.degree q) = δ := by
      rw [← m.toSyn.map_add, ← m.degree_mul hp hq]; exact hpq
    calc m.toSyn (m.degree ((p - m.leadingTerm p) * q))
        ≤ m.toSyn (m.degree (p - m.leadingTerm p)) + m.toSyn (m.degree q) :=
            m.toSyn_degree_mul_le
      _ < m.toSyn (m.degree p) + m.toSyn (m.degree q) :=
            add_lt_add_of_lt_of_le (m.degree_sub_leadingTerm_lt_degree hdeg_ne) le_rfl
      _ = δ := hdeg_sum

/-- When `f' = ∑_G μ'g * g` has degree `< δ` but all terms have degree `≤ δ`, the sum
`∑_{b ∈ B} LT(μ'b) * b` over the top-degree set `B` also has syn-degree `< δ`. -/
private lemma degree_sum_lterms_lt_of_cancel (G : Finset (MvPolynomial σ k))
    (hG0 : ∀ g : ↥G, (g : MvPolynomial σ k) ≠ 0)
    {δ : m.syn} (hδ : ⊥ < δ) {f' : MvPolynomial σ k} {μ' : ↥G → MvPolynomial σ k}
    (hf' : f' = ∑ g : ↥G, μ' g * g.val)
    (hδ' : ∀ g : ↥G, m.toSyn (m.degree (μ' g * g.val)) ≤ δ)
    (hlt_f' : m.toSyn (m.degree f') < δ) :
    let B    := Finset.univ.filter fun b : ↥G => m.toSyn (m.degree (μ' b * b.val)) = δ
    let lterm := fun b : ↥G => m.leadingTerm (μ' b) * b.val
    m.toSyn (m.degree (∑ b ∈ B, lterm b)) < δ := by
  classical
  intro B lterm
  -- Key identity: ∑_B LT(μ'b)*b = ∑_B μ'b*b - ∑_B (μ'b - LT(μ'b))*b
  have hident : ∑ b ∈ B, lterm b =
      ∑ b ∈ B, μ' b * b.val - ∑ b ∈ B, (μ' b - m.leadingTerm (μ' b)) * b.val := by
    rw [← Finset.sum_sub_distrib]
    congr 1; ext b; simp only [lterm]; ring
  rw [hident]
  -- Bound on complement sum: ∑_{Bᶜ} μ'b*b has degree < δ
  have hBc_lt : m.toSyn (m.degree (∑ b ∈ Finset.univ \ B, μ' b * b.val)) < δ := by
    apply degree_sum_lt_of_forall_lt hδ
    intro b hb
    have hnotB : b ∉ B := (Finset.mem_sdiff.mp hb).2
    simp only [B, Finset.mem_filter, Finset.mem_univ, true_and] at hnotB
    exact lt_of_le_of_ne (hδ' b) hnotB
  -- Bound on first sum: ∑_B μ'b*b = f' - ∑_{Bᶜ} μ'b*b, both sides < δ
  have hB_lt : m.toSyn (m.degree (∑ b ∈ B, μ' b * b.val)) < δ := by
    have hfull : ∑ b ∈ B, μ' b * b.val + ∑ b ∈ Finset.univ \ B, μ' b * b.val =
        ∑ g : ↥G, μ' g * g.val := by
      rw [add_comm]; exact Finset.sum_sdiff (Finset.filter_subset _ _)
    have heq : ∑ b ∈ B, μ' b * b.val = f' - ∑ b ∈ Finset.univ \ B, μ' b * b.val := by
      rw [eq_sub_iff_add_eq]; exact hfull.trans hf'.symm
    rw [heq]
    exact lt_of_le_of_lt m.degree_sub_le (sup_lt_iff.mpr ⟨hlt_f', hBc_lt⟩)
  -- Bound on second sum: each tail term (μ'b - LT(μ'b))*b has degree < δ by degree_tail_mul_lt_of_top_degree
  have htail_lt : m.toSyn (m.degree (∑ b ∈ B, (μ' b - m.leadingTerm (μ' b)) * b.val)) < δ := by
    apply degree_sum_lt_of_forall_lt hδ
    intro b hb
    simp only [B, Finset.mem_filter, Finset.mem_univ, true_and] at hb
    have hμb : μ' b ≠ 0 := by
      intro h
      rw [h, zero_mul, degree_zero, map_zero, ← m.bot_eq_zero] at hb
      exact absurd hb hδ.ne
    exact degree_tail_mul_lt_of_top_degree hμb (hG0 b) hδ hb
  -- Combine: deg(A - B) ≤ deg(A) ⊔ deg(B) < δ
  exact lt_of_le_of_lt m.degree_sub_le (sup_lt_iff.mpr ⟨hB_lt, htail_lt⟩)

/-- A scalar multiple of `S(LT(μ'b₁) * b₁, LT(μ'b₂) * b₂)` decomposes as `∑_g ν g * g`
with every term of syn-degree `< δ`, using `hspoly` to reduce `S(b₁, b₂)` and
`sPolynomial_leadingTerm_mul` to shift degrees. -/
private lemma sPolynomial_lterm_mul_reducesToLower (G : Finset (MvPolynomial σ k))
    (hG0 : ∀ g : ↥G, (g : MvPolynomial σ k) ≠ 0)
    (hspoly : ∀ g g' : ↥G,
        m.ReducesToZero (fun p : ↥G => (p : MvPolynomial σ k)) hG0 (m.sPolynomial g g'))
    {δ : m.syn} (hδ : ⊥ < δ) {μ' : ↥G → MvPolynomial σ k}
    (hδ' : ∀ g : ↥G, m.toSyn (m.degree (μ' g * g.val)) ≤ δ)
    {b₁ b₂ : ↥G}
    (hb₁ : m.toSyn (m.degree (μ' b₁ * b₁.val)) = δ)
    (hb₂ : m.toSyn (m.degree (μ' b₂ * b₂.val)) = δ)
    (c : k) :
    ∃ ν : ↥G → MvPolynomial σ k,
      c • m.sPolynomial (m.leadingTerm (μ' b₁) * b₁.val) (m.leadingTerm (μ' b₂) * b₂.val) =
        ∑ g : ↥G, ν g * g.val ∧
      ∀ g : ↥G, m.toSyn (m.degree (ν g * g.val)) < δ := by
  -- Trivial cases
  by_cases hc : c = 0
  · exact ⟨fun _ => 0, by simp [hc], fun g => by simp [m.bot_eq_zero]; exact hδ⟩
  by_cases hS : m.sPolynomial b₁.val b₂.val = 0
  · have hSLT0 : m.sPolynomial (m.leadingTerm (μ' b₁) * b₁.val) (m.leadingTerm (μ' b₂) * b₂.val) = 0 :=
      by rw [m.sPolynomial_leadingTerm_mul, hS, mul_zero]
    exact ⟨fun _ => 0, by simp [hSLT0], fun g => by simp [m.bot_eq_zero]; exact hδ⟩
  -- μ' b₁ and μ' b₂ are nonzero
  have hμ₁ : μ' b₁ ≠ 0 := by
    intro h; simp only [h, zero_mul, degree_zero, map_zero, ← m.bot_eq_zero] at hb₁
    exact hδ.ne hb₁
  have hμ₂ : μ' b₂ ≠ 0 := by
    intro h; simp only [h, zero_mul, degree_zero, map_zero, ← m.bot_eq_zero] at hb₂
    exact hδ.ne hb₂
  -- Unpack hspoly b₁ b₂
  obtain ⟨q, hq_eq, hq_deg⟩ := hspoly b₁ b₂
  -- Rewrite linearCombination as Finset.sum
  have hq_sum : m.sPolynomial b₁.val b₂.val = ∑ g : ↥G, q g * g.val := by
    rw [hq_eq]
    simp only [Finsupp.linearCombination, Finsupp.lsum_apply, Finsupp.sum,
               LinearMap.smulRight_apply, LinearMap.id_coe, id, smul_eq_mul]
    apply Finset.sum_subset (Finset.subset_univ _)
    intro g _ hg
    simp only [Finsupp.mem_support_iff, ne_eq, not_not] at hg; simp [hg]
  -- Set up the monomial M from sPolynomial_leadingTerm_mul
  have hcM_ne : m.leadingCoeff (μ' b₁) * m.leadingCoeff (μ' b₂) ≠ 0 :=
    mul_ne_zero (m.leadingCoeff_ne_zero_iff.mpr hμ₁) (m.leadingCoeff_ne_zero_iff.mpr hμ₂)
  set M := monomial
      ((m.degree (μ' b₁) + m.degree b₁.val) ⊔ (m.degree (μ' b₂) + m.degree b₂.val) -
       m.degree b₁.val ⊔ m.degree b₂.val)
      (m.leadingCoeff (μ' b₁) * m.leadingCoeff (μ' b₂))
  have hM_ne : M ≠ 0 := by
    simp only [M, Ne, monomial_eq_zero]; exact hcM_ne
  -- Factored form: S(LT(μ'b₁)*b₁, LT(μ'b₂)*b₂) = M * S(b₁, b₂)
  have hfactor : m.sPolynomial (m.leadingTerm (μ' b₁) * b₁.val) (m.leadingTerm (μ' b₂) * b₂.val) =
                 M * m.sPolynomial b₁.val b₂.val :=
    m.sPolynomial_leadingTerm_mul (μ' b₁) (μ' b₂) b₁.val b₂.val
  -- S(LT...) ≠ 0
  have hSLT_ne : m.sPolynomial (m.leadingTerm (μ' b₁) * b₁.val) (m.leadingTerm (μ' b₂) * b₂.val) ≠ 0 :=
    hfactor ▸ mul_ne_zero hM_ne hS
  -- Degrees of LT(μ'bᵢ) * bᵢ are both δ
  have hLT₁_ne : m.leadingTerm (μ' b₁) ≠ 0 := by
    simp only [leadingTerm, ne_eq, monomial_eq_zero]
    exact m.leadingCoeff_ne_zero_iff.mpr hμ₁
  have hLT₂_ne : m.leadingTerm (μ' b₂) ≠ 0 := by
    simp only [leadingTerm, ne_eq, monomial_eq_zero]
    exact m.leadingCoeff_ne_zero_iff.mpr hμ₂
  have hdeg_LT₁ : m.toSyn (m.degree (m.leadingTerm (μ' b₁) * b₁.val)) = δ := by
    rw [m.degree_mul hLT₁_ne (hG0 b₁), m.toSyn.map_add, m.degree_leadingTerm,
        ← m.toSyn.map_add, ← m.degree_mul hμ₁ (hG0 b₁)]; exact hb₁
  have hdeg_LT₂ : m.toSyn (m.degree (m.leadingTerm (μ' b₂) * b₂.val)) = δ := by
    rw [m.degree_mul hLT₂_ne (hG0 b₂), m.toSyn.map_add, m.degree_leadingTerm,
        ← m.toSyn.map_add, ← m.degree_mul hμ₂ (hG0 b₂)]; exact hb₂
  have hdeg_eq : m.degree (m.leadingTerm (μ' b₁) * b₁.val) =
                 m.degree (m.leadingTerm (μ' b₂) * b₂.val) :=
    m.toSyn.injective (hdeg_LT₁.trans hdeg_LT₂.symm)
  -- Degree of S(LT...) < δ
  have hSLT_lt : m.toSyn (m.degree (m.sPolynomial (m.leadingTerm (μ' b₁) * b₁.val)
                                                    (m.leadingTerm (μ' b₂) * b₂.val))) < δ := by
    have h := m.degree_sPolynomial_lt_sup_degree hSLT_ne
    rw [hdeg_eq, sup_idem, hdeg_LT₂] at h; exact h
  -- Key bound: m.toSyn (deg M) + m.toSyn (deg S(b₁,b₂)) < δ
  have hkey : m.toSyn (m.degree M) + m.toSyn (m.degree (m.sPolynomial b₁.val b₂.val)) < δ := by
    rw [← m.toSyn.map_add, ← m.degree_mul hM_ne hS, ← hfactor]; exact hSLT_lt
  -- ν g = c • M * q g
  refine ⟨fun g => c • M * q g, ?_, ?_⟩
  · -- Equality: c • S(LT...) = ∑_g (c • M * q g) * g.val
    rw [hfactor, hq_sum, ← smul_mul_assoc, Finset.mul_sum]
    congr 1; ext g; ring
  · -- Degree bound
    intro g
    have hdeg_cM : m.toSyn (m.degree (c • M)) = m.toSyn (m.degree M) := by
      congr 1; simp only [M, smul_monomial, smul_eq_mul]
      classical
      simp only [m.degree_monomial, if_neg (mul_ne_zero hc hcM_ne), if_neg hcM_ne]
    calc m.toSyn (m.degree (c • M * q g * g.val))
        = m.toSyn (m.degree (c • M * (q g * g.val))) := by rw [mul_assoc]
      _ ≤ m.toSyn (m.degree (c • M)) + m.toSyn (m.degree (q g * g.val)) :=
            m.toSyn_degree_mul_le
      _ = m.toSyn (m.degree M) + m.toSyn (m.degree (q g * g.val)) := by rw [hdeg_cM]
      _ ≤ m.toSyn (m.degree M) + m.toSyn (m.degree (m.sPolynomial b₁.val b₂.val)) := by
            gcongr; rw [mul_comm]; exact hq_deg g
      _ < δ := hkey

/-- The double sum `∑_{b₁ ∈ B} ∑_{b₂ ∈ B} c b₁ b₂ • S(LT(μ'b₁)*b₁, LT(μ'b₂)*b₂)` decomposes
as `∑_g ν g * g` with every term of syn-degree `< δ`. -/
private lemma sum_sPolynomial_lterm_reductions (G : Finset (MvPolynomial σ k))
    (hG0 : ∀ g : ↥G, (g : MvPolynomial σ k) ≠ 0)
    (hspoly : ∀ g g' : ↥G,
        m.ReducesToZero (fun p : ↥G => (p : MvPolynomial σ k)) hG0 (m.sPolynomial g g'))
    {δ : m.syn} (hδ : ⊥ < δ) {μ' : ↥G → MvPolynomial σ k}
    (hδ' : ∀ g : ↥G, m.toSyn (m.degree (μ' g * g.val)) ≤ δ)
    (c : ↥G → ↥G → k) :
    let B     := Finset.univ.filter fun b : ↥G => m.toSyn (m.degree (μ' b * b.val)) = δ
    let lterm := fun b : ↥G => m.leadingTerm (μ' b) * b.val
    ∃ ν : ↥G → MvPolynomial σ k,
      ∑ b₁ ∈ B, ∑ b₂ ∈ B, c b₁ b₂ • m.sPolynomial (lterm b₁) (lterm b₂) =
        ∑ g : ↥G, ν g * g.val ∧
      ∀ g : ↥G, m.toSyn (m.degree (ν g * g.val)) < δ := by
  intro B lterm
  classical
  -- For each pair (b₁, b₂) ∈ B × B, sPolynomial_lterm_mul_reducesToLower gives a ν witness
  have hpair : ∀ b₁ ∈ B, ∀ b₂ ∈ B,
      ∃ ν_pair : ↥G → MvPolynomial σ k,
      c b₁ b₂ • m.sPolynomial (lterm b₁) (lterm b₂) = ∑ g : ↥G, ν_pair g * g.val ∧
      ∀ g : ↥G, m.toSyn (m.degree (ν_pair g * g.val)) < δ := by
    intro b₁ hb₁ b₂ hb₂
    simp only [B, Finset.mem_filter, Finset.mem_univ, true_and] at hb₁ hb₂
    exact sPolynomial_lterm_mul_reducesToLower G hG0 hspoly hδ hδ' hb₁ hb₂ (c b₁ b₂)
  -- Pick ν for each pair via Classical.choose
  let ν_pair : ↥G → ↥G → ↥G → MvPolynomial σ k :=
    fun b₁ b₂ g =>
      if hb₁ : b₁ ∈ B then
        if hb₂ : b₂ ∈ B then Classical.choose (hpair b₁ hb₁ b₂ hb₂) g
        else 0
      else 0
  have hν_eq : ∀ b₁ ∈ B, ∀ b₂ ∈ B,
      c b₁ b₂ • m.sPolynomial (lterm b₁) (lterm b₂) = ∑ g : ↥G, ν_pair b₁ b₂ g * g.val := by
    intro b₁ hb₁ b₂ hb₂
    have hunfold : ∀ g : ↥G, ν_pair b₁ b₂ g = Classical.choose (hpair b₁ hb₁ b₂ hb₂) g :=
      fun g => by simp only [ν_pair, dif_pos hb₁, dif_pos hb₂]
    simp_rw [hunfold]
    exact (Classical.choose_spec (hpair b₁ hb₁ b₂ hb₂)).1
  have hν_lt : ∀ b₁ ∈ B, ∀ b₂ ∈ B, ∀ g : ↥G,
      m.toSyn (m.degree (ν_pair b₁ b₂ g * g.val)) < δ := by
    intro b₁ hb₁ b₂ hb₂ g
    have hunfold : ν_pair b₁ b₂ g = Classical.choose (hpair b₁ hb₁ b₂ hb₂) g := by
      simp only [ν_pair, dif_pos hb₁, dif_pos hb₂]
    rw [hunfold]
    exact (Classical.choose_spec (hpair b₁ hb₁ b₂ hb₂)).2 g
  -- ν g = ∑_{b₁∈B} ∑_{b₂∈B} ν_pair b₁ b₂ g
  refine ⟨fun g => ∑ b₁ ∈ B, ∑ b₂ ∈ B, ν_pair b₁ b₂ g, ?_, ?_⟩
  · -- Equality: swap summation order and apply hν_eq
    symm
    calc ∑ g : ↥G, (∑ b₁ ∈ B, ∑ b₂ ∈ B, ν_pair b₁ b₂ g) * g.val
        = ∑ g : ↥G, ∑ b₁ ∈ B, ∑ b₂ ∈ B, ν_pair b₁ b₂ g * g.val := by
              simp_rw [Finset.sum_mul]
      _ = ∑ b₁ ∈ B, ∑ g : ↥G, ∑ b₂ ∈ B, ν_pair b₁ b₂ g * g.val := Finset.sum_comm
      _ = ∑ b₁ ∈ B, ∑ b₂ ∈ B, ∑ g : ↥G, ν_pair b₁ b₂ g * g.val := by
              apply Finset.sum_congr rfl; intro b₁ _; exact Finset.sum_comm
      _ = ∑ b₁ ∈ B, ∑ b₂ ∈ B, c b₁ b₂ • m.sPolynomial (lterm b₁) (lterm b₂) := by
              apply Finset.sum_congr rfl; intro b₁ hb₁
              apply Finset.sum_congr rfl; intro b₂ hb₂
              exact (hν_eq b₁ hb₁ b₂ hb₂).symm
  · -- Degree bound: expand the product then apply degree_sum_lt_of_forall_lt twice
    intro g
    rw [show (∑ b₁ ∈ B, ∑ b₂ ∈ B, ν_pair b₁ b₂ g) * g.val =
          ∑ b₁ ∈ B, ∑ b₂ ∈ B, ν_pair b₁ b₂ g * g.val by simp [Finset.sum_mul]]
    apply degree_sum_lt_of_forall_lt hδ; intro b₁ hb₁
    apply degree_sum_lt_of_forall_lt hδ; intro b₂ hb₂
    exact hν_lt b₁ hb₁ b₂ hb₂ g

/-- **Boss lemma**: when top-degree terms cancel in `f' = ∑ μ'g * g` (i.e. `deg f' < δ`
while all terms have degree `≤ δ`), S-polynomial reduction via `hspoly` yields a new
representation with a strictly smaller syn-degree bound. -/
private lemma exists_lower_degree_representation_after_top_cancel
    (G : Finset (MvPolynomial σ k))
    (hG0 : ∀ g : ↥G, (g : MvPolynomial σ k) ≠ 0)
    (hspoly : ∀ g g' : ↥G,
        m.ReducesToZero (fun p : ↥G => (p : MvPolynomial σ k)) hG0 (m.sPolynomial g g'))
    {δ : m.syn} (hδ : ⊥ < δ) {f' : MvPolynomial σ k} {μ' : ↥G → MvPolynomial σ k}
    (hf' : f' = ∑ g : ↥G, μ' g * g.val)
    (hδ' : ∀ g : ↥G, m.toSyn (m.degree (μ' g * g.val)) ≤ δ)
    (hlt_f' : m.toSyn (m.degree f') < δ) :
    ∃ (δ' : m.syn) (μ'' : ↥G → MvPolynomial σ k),
      δ' < δ ∧ f' = ∑ g : ↥G, μ'' g * g.val ∧
      ∀ g : ↥G, m.toSyn (m.degree (μ'' g * g.val)) ≤ δ' := by
  classical
  let B     := Finset.univ.filter fun b : ↥G => m.toSyn (m.degree (μ' b * b.val)) = δ
  let lterm := fun b : ↥G => m.leadingTerm (μ' b) * b.val
  -- b ∈ B ⟹ μ'b ≠ 0
  have hμ_ne : ∀ b ∈ B, μ' b ≠ 0 := fun b hb h => by
    simp only [B, Finset.mem_filter, Finset.mem_univ, true_and] at hb
    simp only [h, zero_mul, m.degree_zero, map_zero, ← m.bot_eq_zero] at hb
    exact hδ.ne hb
  -- b ∈ B ⟹ m.toSyn(m.degree(lterm b)) = δ
  have hlterm_deg : ∀ b ∈ B, m.toSyn (m.degree (lterm b)) = δ := fun b hb => by
    simp only [B, Finset.mem_filter, Finset.mem_univ, true_and] at hb
    have hμ := hμ_ne b (Finset.mem_filter.mpr ⟨Finset.mem_univ b, hb⟩)
    have hLT_ne : m.leadingTerm (μ' b) ≠ 0 := by
      simp only [leadingTerm, ne_eq, monomial_eq_zero]; exact m.leadingCoeff_ne_zero_iff.mpr hμ
    simp only [lterm]
    rw [m.degree_mul hLT_ne (hG0 b), m.toSyn.map_add, m.degree_leadingTerm,
        ← m.toSyn.map_add, ← m.degree_mul hμ (hG0 b)]; exact hb
  -- ∑_B lterm b has degree < δ
  have hlterm_sum_lt : m.toSyn (m.degree (∑ b ∈ B, lterm b)) < δ :=
    degree_sum_lterms_lt_of_cancel G hG0 hδ hf' hδ' hlt_f'
  -- Decompose ∑_B lterm as double S-poly sum
  obtain ⟨c_pair, hc_pair⟩ :=
    m.sPolynomial_decomposition' lterm (fun b hb => Or.inl (hlterm_deg b hb)) hlterm_sum_lt
  -- Reduce S-poly sum to ∑_g ν_spoly g * g
  obtain ⟨ν_spoly, hν_sum, hν_lt⟩ :=
    sum_sPolynomial_lterm_reductions G hG0 hspoly hδ hδ' c_pair
  have hB_lterm : ∑ b ∈ B, lterm b = ∑ g : ↥G, ν_spoly g * g.val :=
    hc_pair.trans hν_sum
  -- New coefficient function
  let μ'' : ↥G → MvPolynomial σ k :=
    fun g => ν_spoly g + μ' g - if g ∈ B then m.leadingTerm (μ' g) else 0
  -- Every μ''g * g has degree < δ
  have hdeg_μ'' : ∀ g : ↥G, m.toSyn (m.degree (μ'' g * g.val)) < δ := fun g => by
    show m.toSyn (m.degree
        ((ν_spoly g + μ' g - if g ∈ B then m.leadingTerm (μ' g) else 0) * g.val)) < δ
    by_cases hgB : g ∈ B
    · simp only [hgB, ite_true]
      rw [show (ν_spoly g + μ' g - m.leadingTerm (μ' g)) * g.val =
              ν_spoly g * g.val + (μ' g - m.leadingTerm (μ' g)) * g.val from by ring]
      exact lt_of_le_of_lt m.degree_add_le
        (sup_lt_iff.mpr ⟨hν_lt g,
          degree_tail_mul_lt_of_top_degree (hμ_ne g hgB) (hG0 g) hδ
            ((Finset.mem_filter.mp hgB).2)⟩)
    · simp only [hgB, ite_false, sub_zero]
      rw [show (ν_spoly g + μ' g) * g.val = ν_spoly g * g.val + μ' g * g.val from by ring]
      exact lt_of_le_of_lt m.degree_add_le
        (sup_lt_iff.mpr ⟨hν_lt g,
          lt_of_le_of_ne (hδ' g) (by
            simp only [B, Finset.mem_filter, Finset.mem_univ, true_and] at hgB; exact hgB)⟩)
  refine ⟨Finset.univ.sup fun g : ↥G => m.toSyn (m.degree (μ'' g * g.val)), μ'', ?_, ?_, ?_⟩
  · -- δ' < δ
    exact (Finset.sup_lt_iff hδ).mpr (fun g _ => hdeg_μ'' g)
  · -- f' = ∑_g μ''g * g.val
    rw [hf']
    symm
    calc ∑ g : ↥G, μ'' g * g.val
        = ∑ g : ↥G,
              (ν_spoly g * g.val + μ' g * g.val -
               (if g ∈ B then m.leadingTerm (μ' g) * g.val else 0)) := by
            apply Finset.sum_congr rfl; intro g _
            simp only [μ'']; split_ifs <;> ring
      _ = ∑ g : ↥G, ν_spoly g * g.val + ∑ g : ↥G, μ' g * g.val -
            ∑ g : ↥G, (if g ∈ B then m.leadingTerm (μ' g) * g.val else 0) := by
            rw [Finset.sum_sub_distrib, Finset.sum_add_distrib]
      _ = ∑ g : ↥G, ν_spoly g * g.val + ∑ g : ↥G, μ' g * g.val -
            ∑ g : ↥G, ν_spoly g * g.val := by
            congr 1
            rw [Finset.sum_ite_mem, Finset.univ_inter]
            exact hB_lterm
      _ = ∑ g : ↥G, μ' g * g.val := by ring
  · -- ∀ g, m.toSyn(m.degree(μ''g * g.val)) ≤ δ'
    intro g; exact Finset.le_sup (f := fun g => m.toSyn (m.degree (μ'' g * g.val))) (Finset.mem_univ g)

-- Key induction lemma for buchberger_criterion (←):
-- For any representation f' = ∑ μ' g * g with max m.syn-degree ≤ δ and f' ≠ 0,
-- some nonzero g₀ ∈ G satisfies m.degree g₀ ≤ m.degree f'.
-- Extracted as a private lemma to avoid isDefEq elaboration timeouts from the
-- complex local context inside buchberger_criterion.
private lemma buchberger_key (G : Finset (MvPolynomial σ k))
    (hG0 : ∀ g : ↥G, (g : MvPolynomial σ k) ≠ 0)
    (hspoly : ∀ g : ↥G, ∀ g' : ↥G,
        m.ReducesToZero (fun p : ↥G => (p : MvPolynomial σ k)) hG0 (m.sPolynomial g g'))
    : ∀ (δ : m.syn) (f' : MvPolynomial σ k) (μ' : ↥G → MvPolynomial σ k),
        f' = ∑ g : ↥G, μ' g * g.val →
        (∀ g : ↥G, m.toSyn (m.degree (μ' g * g.val)) ≤ δ) →
        f' ≠ 0 →
        ∃ si ∈ m.degree '' ((G : Set (MvPolynomial σ k)) \ {(0 : MvPolynomial σ k)}),
            si ≤ m.degree f' := by
  intro δ
  apply m.wf.wf.induction (a := δ)
  intro δ ih f' μ' hf' hδ' hf'0
  by_cases hcaseA : m.toSyn (m.degree f') = δ
  · -- Case A: some summand achieves max degree = m.degree f'.
    have hcoeff : ∃ g₀ : ↥G, (μ' g₀ * g₀.val).coeff (m.degree f') ≠ 0 := by
      by_contra hall
      push_neg at hall
      have hzero : f'.coeff (m.degree f') = 0 := by
        nth_rw 2 [hf']
        rw [coeff_sum]
        exact Finset.sum_eq_zero (fun g _ => hall g)
      exact m.leadingCoeff_ne_zero_iff.mpr hf'0 hzero
    obtain ⟨g₀, hg₀coeff⟩ := hcoeff
    have hg₀supp : m.degree f' ∈ (μ' g₀ * g₀.val).support := mem_support_iff.mpr hg₀coeff
    have hle : m.toSyn (m.degree f') ≤ m.toSyn (m.degree (μ' g₀ * g₀.val)) :=
      m.le_degree hg₀supp
    have heqdeg : m.degree (μ' g₀ * g₀.val) = m.degree f' :=
      m.toSyn.injective (le_antisymm (hcaseA ▸ hδ' g₀) hle)
    have hg₀ne : (g₀.val : MvPolynomial σ k) ≠ 0 := by intro h; simp [h] at hg₀coeff
    have hμ₀ne : μ' g₀ ≠ 0 := by intro h; simp [h] at hg₀coeff
    refine ⟨m.degree g₀.val, ⟨g₀.val, ⟨Finset.mem_coe.mpr g₀.2, hg₀ne⟩, rfl⟩, ?_⟩
    calc m.degree g₀.val
        ≤ m.degree (μ' g₀) + m.degree g₀.val := by
              rw [Finsupp.le_iff]; intro i _
              simp only [Finsupp.add_apply]; exact Nat.le_add_left _ _
      _ = m.degree (μ' g₀ * g₀.val) := (m.degree_mul hμ₀ne hg₀ne).symm
      _ = m.degree f' := heqdeg
  · -- Case B: m.toSyn(m.degree f') < δ — top-degree terms cancel.
    classical
    have hlt_f' : m.toSyn (m.degree f') < δ :=
      lt_of_le_of_ne (hf' ▸ m.degree_sum_le.trans (Finset.sup_le fun g _ => hδ' g)) hcaseA
    have hδ_pos : ⊥ < δ := bot_le.trans_lt hlt_f'
    let B : Finset ↥G := Finset.univ.filter fun b => m.toSyn (m.degree (μ' b * b.val)) = δ
    suffices ∃ (δ' : m.syn) (μ'' : ↥G → MvPolynomial σ k),
        δ' < δ ∧ f' = ∑ g : ↥G, μ'' g * g.val ∧
        ∀ g : ↥G, m.toSyn (m.degree (μ'' g * g.val)) ≤ δ' by
      obtain ⟨δ', μ'', hlt, hf'', hbd⟩ := this
      exact ih δ' hlt f' μ'' hf'' hbd hf'0
    by_cases hB : B = ∅
    · -- B1: all terms already < δ
      have hall : ∀ g : ↥G, m.toSyn (m.degree (μ' g * g.val)) < δ := by
        intro g; apply lt_of_le_of_ne (hδ' g); intro h
        exact absurd (Finset.mem_filter.mpr ⟨Finset.mem_univ g, h⟩) (hB ▸ Finset.notMem_empty g)
      exact ⟨Finset.univ.sup fun g : ↥G => m.toSyn (m.degree (μ' g * g.val)),
        μ',
        (Finset.sup_lt_iff hδ_pos).mpr (fun g _ => hall g),
        hf',
        fun g => Finset.le_sup (f := fun g : ↥G => m.toSyn (m.degree (μ' g * g.val)))
                  (Finset.mem_univ g)⟩
    -- B2: top-degree terms present — delegate to boss lemma.
    exact exists_lower_degree_representation_after_top_cancel G hG0 hspoly hδ_pos hf' hδ' hlt_f'

set_option maxHeartbeats 4000000 in
/-- **Buchberger's Criterion** (Hassett Thm 2.3.2 / Cox–Little–O'Shea Thm 6, §2.6).
`G` is a Gröbner basis for `Ideal.span G` iff every S-polynomial `S(g, g')` reduces
to 0 modulo `G`.

*Key ingredient from Mathlib*: `MonomialOrder.sPolynomial_decomposition` gives the
algebraic decomposition used in the (←) direction. -/
theorem buchberger_criterion (G : Finset (MvPolynomial σ k))
    (hG0 : ∀ g : G, (g : MvPolynomial σ k) ≠ 0) :
    m.IsGroebnerBasis (Ideal.span (G : Set (MvPolynomial σ k))) G ↔
    ∀ g : G, ∀ g' : G,

      m.ReducesToZero (fun p : G => (p : MvPolynomial σ k)) hG0
        (m.sPolynomial g g') := by
  constructor
  · -- (→) If G is a Gröbner basis, every S-polynomial lies in Ideal.span G and reduces to 0.
    intro hGbasis g g'
    apply (mem_ideal_iff_reducesToZero _ _ hGbasis hG0 _).mp
    -- S(g, g') = monomial * g − monomial * g' lies in Ideal.span G.
    simp only [sPolynomial]
    exact Ideal.sub_mem _
      (Ideal.mul_mem_left _ _ (Ideal.subset_span (Finset.mem_coe.mpr g.2)))
      (Ideal.mul_mem_left _ _ (Ideal.subset_span (Finset.mem_coe.mpr g'.2)))
  · -- (←) Buchberger's criterion: all S-polynomials reduce to 0 implies G is a Gröbner basis.
    intro hspoly
    -- Part 1: G ⊆ Ideal.span G is trivial.
    have hmem : ∀ g ∈ G, g ∈ Ideal.span (G : Set (MvPolynomial σ k)) :=
      fun g hg => Ideal.subset_span (Finset.mem_coe.mpr hg)
    -- Part 2: initialIdeal (Ideal.span G) = Ideal.span (leadingTerm '' G).
    -- (≥) holds by span_leadingTerms_le_initialIdeal.
    -- (≤) is proved by WF induction via buchberger_key.
    suffices hinit : m.initialIdeal (Ideal.span (G : Set (MvPolynomial σ k))) =
        Ideal.span (m.leadingTerm '' (G : Set (MvPolynomial σ k))) from ⟨hmem, hinit⟩
    apply le_antisymm
    · -- Apply key lemma: close the initialIdeal ≤ goal.
      delta initialIdeal
      rw [Ideal.span_le]
      rintro _ ⟨f, hf, rfl⟩
      by_cases hf0 : f = 0
      · simp [hf0]
      classical
      rw [SetLike.mem_coe, span_leadingTerm_eq_span_leadingMonomial, mem_ideal_span_monomial_image]
      intro d hd
      have hd_eq : d = m.degree f := by
        simp only [leadingTerm, support_monomial,
                   m.leadingCoeff_ne_zero_iff.mpr hf0, ite_false,
                   Finset.mem_singleton] at hd
        exact hd
      subst hd_eq
      obtain ⟨μ, hμ⟩ := Submodule.mem_span_finset'.mp hf
      simp only [smul_eq_mul] at hμ
      exact buchberger_key G hG0 hspoly
        (Finset.univ.sup fun g : ↥G => m.toSyn (m.degree (μ g * g.val)))
        f μ hμ.symm
        (fun g => Finset.le_sup (f := fun g : ↥G => m.toSyn (m.degree (μ g * g.val)))
          (Finset.mem_univ g))
        hf0
    · exact span_leadingTerms_le_initialIdeal (G : Set (MvPolynomial σ k))

/-! ### 7. Existence of Gröbner Bases -/

/-- **Every ideal has a Gröbner basis** (Hassett Thm 2.2.4).
`MvPolynomial σ k` is Noetherian for finite `σ` (Hilbert Basis Theorem);
Buchberger's algorithm terminates and produces a Gröbner basis. -/
theorem groebner_basis_exists [Finite σ] (I : Ideal (MvPolynomial σ k)) :
    ∃ G : Finset (MvPolynomial σ k), m.IsGroebnerBasis I G := by
  classical
  -- MvPolynomial σ k is Noetherian (Hilbert Basis Theorem).
  haveI : IsNoetherianRing (MvPolynomial σ k) := MvPolynomial.isNoetherianRing
  -- The initial ideal is finitely generated; extract generators S.
  obtain ⟨S, hS⟩ := IsNoetherian.noetherian (m.initialIdeal I)
  -- S ⊆ m.initialIdeal I = span (lt '' I). Find finite T ⊆ lt '' I with S ⊆ span T.
  have hS_in : (S : Set (MvPolynomial σ k)) ⊆
      Submodule.span (MvPolynomial σ k) (m.leadingTerm '' (I : Set (MvPolynomial σ k))) := by
    intro x hx
    have hmem : x ∈ Submodule.span (MvPolynomial σ k) (S : Set (MvPolynomial σ k)) :=
      Submodule.subset_span hx
    rw [hS] at hmem; exact hmem
  obtain ⟨T, hT_sub, hST⟩ := Submodule.subset_span_finite_of_subset_span hS_in
  -- span T = m.initialIdeal I.
  have hT_span : m.initialIdeal I = Ideal.span ↑T := by
    apply le_antisymm
    · exact hS.symm ▸ Ideal.span_le.mpr hST
    · exact Ideal.span_mono hT_sub
  -- For each t ∈ T pick a preimage f_t ∈ I with lt(f_t) = t.
  have hpick : ∀ t : ↥T, ∃ f : MvPolynomial σ k, f ∈ I ∧ m.leadingTerm f = ↑t := by
    rintro ⟨t, ht⟩
    obtain ⟨f, hf, hft⟩ := hT_sub (Finset.mem_coe.mpr ht)
    exact ⟨f, SetLike.mem_coe.mp hf, hft⟩
  let pick : ↥T → MvPolynomial σ k := fun t => (hpick t).choose
  -- G = {pick t | t ∈ T} is the Gröbner basis.
  refine ⟨Finset.univ.image pick, ?_, ?_⟩
  · -- Every element of G lies in I.
    intro g hg
    simp only [Finset.mem_image, Finset.mem_univ, true_and] at hg
    obtain ⟨t, rfl⟩ := hg
    exact (hpick t).choose_spec.1
  · -- The initial ideal is spanned by the leading terms of G.
    rw [hT_span]
    congr 1
    ext x
    simp only [Set.mem_image, Finset.coe_image, Finset.coe_univ, Set.image_univ,
               Set.mem_range, Finset.mem_coe]
    constructor
    · intro hx
      exact ⟨pick ⟨x, hx⟩, ⟨⟨x, hx⟩, rfl⟩, (hpick ⟨x, hx⟩).choose_spec.2⟩
    · rintro ⟨_, ⟨t, rfl⟩, hx⟩
      rw [← hx, (hpick t).choose_spec.2]; exact t.2

/-! ### 8. Reduced Gröbner Bases -/

/-- A Gröbner basis `G` is **reduced** if every `g ∈ G` is monic and no monomial of `g`
is divisible by the leading monomial of any other `g' ∈ G`. -/
def IsReducedGroebnerBasis (I : Ideal (MvPolynomial σ k))
    (G : Finset (MvPolynomial σ k)) : Prop :=
  m.IsGroebnerBasis I G ∧
  (∀ g ∈ G, m.Monic g) ∧
  (∀ g ∈ G, ∀ c ∈ (g : MvPolynomial σ k).support,
    ∀ g' ∈ G, g ≠ g' → ¬ m.degree g' ≤ c)

/-- A reduced Gröbner basis is a Gröbner basis. -/
lemma IsReducedGroebnerBasis.isGroebnerBasis {I : Ideal (MvPolynomial σ k)}
    {G : Finset (MvPolynomial σ k)} (hG : m.IsReducedGroebnerBasis I G) :
    m.IsGroebnerBasis I G := hG.1

/-! #### Lemmas for uniqueness of reduced Gröbner bases -/

/-- Every element of a reduced Gröbner basis is nonzero (it is monic). -/
private lemma rgb_ne_zero {I : Ideal (MvPolynomial σ k)}
    {G : Finset (MvPolynomial σ k)} (hG : m.IsReducedGroebnerBasis I G)
    {g : MvPolynomial σ k} (hg : g ∈ G) : g ≠ 0 :=
  (hG.2.1 g hg).ne_zero

/-- The leading monomial of each element of a reduced Gröbner basis lies in its support. -/
private lemma rgb_degree_mem_support {I : Ideal (MvPolynomial σ k)}
    {G : Finset (MvPolynomial σ k)} (hG : m.IsReducedGroebnerBasis I G)
    {g : MvPolynomial σ k} (hg : g ∈ G) : m.degree g ∈ g.support :=
  m.degree_mem_support (rgb_ne_zero hG hg)

/-- In a reduced Gröbner basis, no LM of one element divides (pointwise `≤`) the LM of a
distinct element. -/
private lemma rgb_no_lm_div {I : Ideal (MvPolynomial σ k)}
    {G : Finset (MvPolynomial σ k)} (hG : m.IsReducedGroebnerBasis I G)
    {g g' : MvPolynomial σ k} (hg : g ∈ G) (hg' : g' ∈ G) (hne : g ≠ g') :
    ¬ m.degree g' ≤ m.degree g :=
  hG.2.2 g hg (m.degree g) (rgb_degree_mem_support hG hg) g' hg' hne

/-- Two monic polynomials sharing the same leading monomial but unequal have strictly
smaller monomial-order degree in their difference. -/
private lemma rgb_diff_lt {g g' : MvPolynomial σ k}
    (hg : m.Monic g) (hg' : m.Monic g')
    (hdeg : m.degree g = m.degree g') (hne : g ≠ g') :
    m.toSyn (m.degree (g - g')) < m.toSyn (m.degree g) := by
  have hne' : g - g' ≠ 0 := sub_ne_zero.mpr hne
  have hle : m.toSyn (m.degree (g - g')) ≤ m.toSyn (m.degree g) :=
    m.degree_sub_le.trans (by rw [← hdeg, sup_idem])
  have hdeg_ne : m.degree (g - g') ≠ m.degree g := by
    intro heq
    have hmem : m.degree g ∈ (g - g').support := heq ▸ m.degree_mem_support hne'
    have hcoeff : (g - g').coeff (m.degree g) = 0 := by
      rw [coeff_sub, hg.coeff_degree, hdeg, hg'.coeff_degree, sub_self]
    exact absurd hcoeff (Finsupp.mem_support_iff.mp hmem)
  exact lt_of_le_of_ne hle (m.toSyn.injective.ne hdeg_ne)

/-- For two reduced Gröbner bases of the same ideal, each element of one has an element with
the same leading monomial in the other. -/
private lemma rgb_lm_match {I : Ideal (MvPolynomial σ k)}
    {G G' : Finset (MvPolynomial σ k)}
    (hG : m.IsReducedGroebnerBasis I G) (hG' : m.IsReducedGroebnerBasis I G')
    {g : MvPolynomial σ k} (hg : g ∈ G) :
    ∃ g' ∈ G', m.degree g' = m.degree g := by
  -- g ∈ I, g ≠ 0
  have hg_mem : g ∈ I := hG.1.mem_ideal hg
  have hg0 : g ≠ 0 := rgb_ne_zero hG hg
  -- G' is a GB: some g₀ ∈ G' has LM(g₀) ≤ LM(g)
  obtain ⟨g₀, hg₀_in, -, hg₀_le⟩ := hG'.1.leadingDeg_dvd hg_mem hg0
  -- g₀ ∈ I, g₀ ≠ 0
  have hg₀_mem : g₀ ∈ I := hG'.1.mem_ideal hg₀_in
  have hg₀_ne : g₀ ≠ 0 := rgb_ne_zero hG' hg₀_in
  -- G is a GB: some g₁ ∈ G has LM(g₁) ≤ LM(g₀) ≤ LM(g)
  obtain ⟨g₁, hg₁_in, -, hg₁_le⟩ := hG.1.leadingDeg_dvd hg₀_mem hg₀_ne
  -- No other element of G can have LM ≤ LM(g), so g₁ = g
  have hg₁_eq : g₁ = g := by
    by_contra hne
    exact absurd (le_trans hg₁_le hg₀_le) (rgb_no_lm_div hG hg hg₁_in (Ne.symm hne))
  -- Hence LM(g₀) = LM(g)
  subst hg₁_eq
  exact ⟨g₀, hg₀_in, le_antisymm hg₀_le hg₁_le⟩

/-- If two elements, one from each of two reduced Gröbner bases of the same ideal, share the
same leading monomial, then they are equal. -/
private lemma rgb_element_eq {I : Ideal (MvPolynomial σ k)}
    {G G' : Finset (MvPolynomial σ k)}
    (hG : m.IsReducedGroebnerBasis I G) (hG' : m.IsReducedGroebnerBasis I G')
    {g g' : MvPolynomial σ k} (hg : g ∈ G) (hg' : g' ∈ G')
    (hdeg : m.degree g = m.degree g') : g = g' := by
  by_contra hne
  -- g - g' ∈ I, nonzero; let d = LM(g - g') < LM(g)
  have hdiff_mem : g - g' ∈ I :=
    I.sub_mem (hG.1.mem_ideal hg) (hG'.1.mem_ideal hg')
  have hdiff_ne : g - g' ≠ 0 := sub_ne_zero.mpr hne
  let d := m.degree (g - g')
  have hd_lt : m.toSyn d < m.toSyn (m.degree g) :=
    rgb_diff_lt (hG.2.1 g hg) (hG'.2.1 g' hg') hdeg hne
  -- d ∈ support(g - g'), so the coefficient at d is nonzero
  have hd_supp : d ∈ (g - g').support := m.degree_mem_support hdiff_ne
  -- d ∈ support(g) or support(g'): if g.coeff d = 0, then g'.coeff d ≠ 0 and vice versa
  rcases eq_or_ne (g.coeff d) 0 with hgd | hgd
  · -- Case d ∈ support(g'): use G' to find a basis element with LM ≤ d
    have hg'd : g'.coeff d ≠ 0 := by
      intro h; apply Finsupp.mem_support_iff.mp hd_supp
      have : (g - g').coeff d = 0 := by rw [coeff_sub, hgd, h, sub_self]
      exact this
    have hd_in_g' : d ∈ g'.support := Finsupp.mem_support_iff.mpr hg'd
    obtain ⟨g₀, hg₀_in, -, hg₀_le⟩ := hG'.1.leadingDeg_dvd hdiff_mem hdiff_ne
    rcases eq_or_ne g₀ g' with rfl | hne₀
    · -- LM(g') ≤ d < LM(g') — contradiction
      exact absurd (m.toSyn_monotone hg₀_le) (not_le.mpr (hdeg ▸ hd_lt))
    · -- Reducedness of G' forbids any other g₀ from having LM ≤ d ∈ support(g')
      exact hG'.2.2 g' hg' d hd_in_g' g₀ hg₀_in hne₀.symm hg₀_le
  · -- Case d ∈ support(g): use G to find a basis element with LM ≤ d
    have hd_in_g : d ∈ g.support := Finsupp.mem_support_iff.mpr hgd
    obtain ⟨g₀, hg₀_in, -, hg₀_le⟩ := hG.1.leadingDeg_dvd hdiff_mem hdiff_ne
    rcases eq_or_ne g₀ g with rfl | hne₀
    · -- LM(g) ≤ d < LM(g) — contradiction
      exact absurd (m.toSyn_monotone hg₀_le) (not_le.mpr hd_lt)
    · -- Reducedness of G forbids any other g₀ from having LM ≤ d ∈ support(g)
      exact hG.2.2 g hg d hd_in_g g₀ hg₀_in hne₀.symm hg₀_le

/-- Every reduced Gröbner basis of an ideal is a subset of every other. -/
private lemma rgb_subset {I : Ideal (MvPolynomial σ k)}
    {G G' : Finset (MvPolynomial σ k)}
    (hG : m.IsReducedGroebnerBasis I G) (hG' : m.IsReducedGroebnerBasis I G') :
    G ⊆ G' := fun g hg => by
  obtain ⟨g', hg', hdeg'⟩ := rgb_lm_match hG hG' hg
  exact (rgb_element_eq hG hG' hg hg' hdeg'.symm) ▸ hg'

/-! #### Existence of reduced Gröbner bases -/

/-- From any Gröbner basis a minimal one exists: no LM of one element pointwise-divides
another's LM. -/
private lemma gb_minimal_exists [Finite σ] (I : Ideal (MvPolynomial σ k)) :
    ∃ G : Finset (MvPolynomial σ k),
      m.IsGroebnerBasis I G ∧
      (∀ g : ↥G, (g : MvPolynomial σ k) ≠ 0) ∧
      (∀ g ∈ G, ∀ g' ∈ G, g ≠ g' → ¬ m.degree g' ≤ m.degree g) := by
  sorry

/-- A minimal Gröbner basis can be made monic without losing the Gröbner or minimality property
(divide each element by its leading coefficient). -/
private lemma gb_monic_minimal_exists [Finite σ] (I : Ideal (MvPolynomial σ k)) :
    ∃ G : Finset (MvPolynomial σ k),
      m.IsGroebnerBasis I G ∧
      (∀ g ∈ G, m.Monic g) ∧
      (∀ g ∈ G, ∀ g' ∈ G, g ≠ g' → ¬ m.degree g' ≤ m.degree g) := by
  sorry

/-- Reducing each element of a monic minimal Gröbner basis modulo the rest yields a reduced
Gröbner basis. -/
private lemma gb_reduce_to_rgb [Finite σ] (I : Ideal (MvPolynomial σ k))
    {G : Finset (MvPolynomial σ k)}
    (hGbasis : m.IsGroebnerBasis I G)
    (hGmonic : ∀ g ∈ G, m.Monic g)
    (hGmin : ∀ g ∈ G, ∀ g' ∈ G, g ≠ g' → ¬ m.degree g' ≤ m.degree g) :
    ∃ G' : Finset (MvPolynomial σ k), m.IsReducedGroebnerBasis I G' := by
  sorry

/-- **Existence of a reduced Gröbner basis** for every nonzero ideal. -/
private lemma rgb_exists [Finite σ] (I : Ideal (MvPolynomial σ k)) (hI : I ≠ ⊥) :
    ∃ G : Finset (MvPolynomial σ k), m.IsReducedGroebnerBasis I G := by
  obtain ⟨G, hGbasis, hGmonic, hGmin⟩ := gb_monic_minimal_exists I
  exact gb_reduce_to_rgb I hGbasis hGmonic hGmin

/-- **Uniqueness of Reduced Gröbner Bases** (Hassett Thm 2.3.4).
Every nonzero ideal has a unique reduced Gröbner basis. -/
theorem reduced_groebner_basis_unique [Finite σ]
    (I : Ideal (MvPolynomial σ k)) (hI : I ≠ ⊥) :
    ∃! G : Finset (MvPolynomial σ k), m.IsReducedGroebnerBasis I G := by
  obtain ⟨G, hG⟩ := rgb_exists I hI
  exact ⟨G, hG, fun G' hG' => Finset.Subset.antisymm (rgb_subset hG' hG) (rgb_subset hG hG')⟩

/-! ### 9. Basic properties of S-polynomials -/

/-- S-polynomial is antisymmetric. -/
lemma sPolynomial_antisymm_eq (f g : MvPolynomial σ k) :
    m.sPolynomial f g = -m.sPolynomial g f :=
  m.sPolynomial_antisymm f g

/-- S-polynomial of a polynomial with itself is zero. -/
lemma sPolynomial_self_eq_zero (f : MvPolynomial σ k) :
    m.sPolynomial f f = 0 :=
  m.sPolynomial_self f

/-- The degree of a nonzero S-polynomial is strictly less than the sup of the input degrees. -/
lemma degree_sPolynomial_lt {f g : MvPolynomial σ k}
    (h : m.sPolynomial f g ≠ 0) :
    m.degree (m.sPolynomial f g) ≺[m] m.degree f ⊔ m.degree g :=
  m.degree_sPolynomial_lt_sup_degree h

end MonomialOrder
